name: api_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  pull_to_refresh_flutter3: ^2.0.2

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Networking
  pretty_dio_logger: ^1.3.1
  logger: ^2.3.0
  dio: ^5.5.0+1
  retrofit: ^4.1.0

  # Json Serialization
  json_annotation: ^4.9.0
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  http: ^1.2.2
  audioplayers: ^6.1.0
  


flutter:
  uses-material-design: true

  assets:
    - assets/
